server:
  port: 8081

# Spring Core
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sample
    username: root
    password: root

# Doma2 Reference URL <https://github.com/domaframework/doma-spring-boot>
doma:
  dialect: mysql
  sql-file-repository: no_cache
